### ISSUE TITLE
Additional YAML fields

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#205]
We have [defined a YAML format](https://gedcom.io/terms/format) that covers most of what the standard says about the various concepts it defines, with additional fields for UI design (`help text` and `label`) and for extensions (`documentation` and `extension tags`). But we might want to add more:

- Fields to track versions of the official standard; for example, the `SUBN` record might have
  ```yaml
  standardized in: "5.4"
  removed from: "7.0"
  ```

- Fields to track deprecation; for example EXID might have something like
  ```yaml
  substructures:
    "https://gedcom.io/terms/v7/EXID-TYPE": "{0:1}"
  
  deprecated unless:
    substructures:
      "https://gedcom.io/terms/v7/EXID-TYPE": "{1:1}"
  ```

- Fields to track application support; for example according to [GEDCOM-L's list of extension tags](https://wiki.genealogy.net/GEDCOM/_Nutzerdef-Tag) and using the strings those tools put in their `HEAD.SOUR`, `_ADPN` might have the following
  ```yaml
  supported by:
    PAF: "5"
    BROSKEEP: "6"
  ```

We might also want to add new types; for example

- `type: product` to document `HEAD.SOUR` values and lists of what the product supports
- `type: tag` to provide a master list of all known uses of a given tag
- `type: translations` to provide a master list of either (a) links to YAML files in other languages or (b) translations of user-facing text (`label` and `help text`) or (c) both
