### ISSUE TITLE
uri-def.py doesn't handle br in table correctly

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#395]
Since switching to `mdformat` to create YAML files (see #385) a small formatting error in uri-def.py has come to light related to tables that have `<br/>` elements.

Example:

This table row:

| Value | Meaning |
| :---- | :------ |
| `HUSB` | Adopted by the `HUSB` of the `FAM` pointed to by `FAMC`.<br/>The URI of this value is `g7:enum-ADOP-HUSB` |

should create this YAML

```yaml
uri: https://gedcom.io/terms/v7/enum-ADOP-HUSB

specification:
  - Adopted by the `HUSB` of the `FAM` pointed to by `FAMC`.
```

but creates this YAML instead

```yaml
uri: https://gedcom.io/terms/v7/enum-ADOP-HUSB

specification:
  - Adopted by the `HUSB` of the `FAM` pointed to by `FAMC`.<br/>
```
